### PR TITLE
Extending Dockerfile with DETR dependencies.

### PR DESCRIPTION
**Pull request by picekl**

### CODE REVIEW

**Comment by aCampello** [comment]
Exciting! :shipit:

**Review by aCampello — APPROVED** [review]
LGTM if It works... - merge when you want

**Review by JBlaschke — COMMENTED** [review]
Approve!

**Comment by JBlaschke** [comment]
FTR -- we now have the `cuda-10.0`, `cuda-10.1`, and `cuda-10.2` branches to keep track of that

**Pull request merged**
